// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuYN21_ZuGO-hkipcfmF0WP7hGohQ6aOY',
    appId: '1:605813972051:android:6760c435e592311742faa6',
    messagingSenderId: '605813972051',
    projectId: 'stadtnavi-ludwigsburg',
    storageBucket: 'stadtnavi-ludwigsburg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3I7Udby7aspJKIHOb-ZPhQMwU4gmpMhk',
    appId: '1:605813972051:ios:6fbb0f8e8e4e742142faa6',
    messagingSenderId: '605813972051',
    projectId: 'stadtnavi-ludwigsburg',
    storageBucket: 'stadtnavi-ludwigsburg.appspot.com',
    iosClientId: '605813972051-9niud7u7b03b5648qmkinhtp2r1tr84d.apps.googleusercontent.com',
    iosBundleId: 'de.stadtnavi.ludwigsburg',
  );
}
