// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-e0JTbDH04UAZlyUj47LoJQBDBYW29dk',
    appId: '1:275011808952:android:ee8e3e38d0fc339f3b4e4d',
    messagingSenderId: '275011808952',
    projectId: 'stadtnavi-ludwigsburg-internal',
    storageBucket: 'stadtnavi-ludwigsburg-internal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcgFCaVZfg8QbSEBRKTZFYA0jyJ1hbj3o',
    appId: '1:275011808952:ios:e6927cc919f7e4d23b4e4d',
    messagingSenderId: '275011808952',
    projectId: 'stadtnavi-ludwigsburg-internal',
    storageBucket: 'stadtnavi-ludwigsburg-internal.appspot.com',
    iosClientId: '275011808952-rcap9mvaqk8nsl57d1tpgkhaik4u958n.apps.googleusercontent.com',
    iosBundleId: 'de.stadtnavi.ludwigsburg.internal',
  );
}
