// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBxw003OV3h5Zq7-9f-6J5hxuCuMl3Mc0',
    appId: '1:624400633028:android:006cf714ace4f09bb50d91',
    messagingSenderId: '624400633028',
    projectId: 'stadtnavi-herrenberg-int-dfbbd',
    storageBucket: 'stadtnavi-herrenberg-int-dfbbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb1vtCqGIgVYMYSgBzTwVp1fGNLL2WbK8',
    appId: '1:624400633028:ios:40a720ec8dab28a1b50d91',
    messagingSenderId: '624400633028',
    projectId: 'stadtnavi-herrenberg-int-dfbbd',
    storageBucket: 'stadtnavi-herrenberg-int-dfbbd.appspot.com',
    iosClientId: '624400633028-i6sg6gb5hbpoqsfquq8h1ehq33gss0h4.apps.googleusercontent.com',
    iosBundleId: 'de.stadtnavi.herrenberg.internal',
  );
}
