# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
    # TODO: connect with some custom hooks
    # slack(
    #   message: 'Successfully distributed a new beta build to TestFlight',
    #   success: true,
    #   slack_url: "https://hooks.slack.com/services/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"
    # )
  end
end
